### PR TITLE
Incorporate quicksilver and lammps into QAHPC structure

### PR DESCRIPTION
**Pull request by martyitz**

### CODE REVIEW

**Comment by martyitz** [comment]
Friday, you said it would be OK, as long as it wasn’t in the build area.

I see you just closed the MR.  How do I undo my push to my branch?

I’m not willing to duplicate the build recipes.  I’m willing to have the QA.<dir> scripts and the QATESTS files (renamed to
QATESTS.<dir> in the QAHPCT repo, when I get around to creating it.  It will also need a QAMODULES.<dir> file eventually.

	M

**Comment by jmellorcrummey** [comment]
On Friday, I said a design where you didn't need to put QA files into a build directory was fine. I NEVER intended that to mean that putting QA files into our tutorial examples directories was fine.

I recommend having a tree of "tutorial example" QA files in a QA repository. Then, you can check out the hpctoolkit-tutorial-examples repository as a "subproject" of the QA tree, build the tutorial examples where you expect them, and then run the QA scripts on them.

**Comment by martyitz** [comment]
> On Jan 31, 2024, at 14:19, John Mellor-Crummey ***@***.***> wrote:
> 
> 
> On Friday, I said a design where you didn't need to put QA files into a build directory was fine. I NEVER intended that to mean that putting QA files into our tutorial examples directories was fine.
> 
I remember specifically asking, and you said it was OK.  Either you misunderstood my question, or I misunderstood your answer.
> I recommend having a tree of "tutorial example" QA files in a QA repository. Then, you can check out the hpctoolkit-tutorial-examples repository as a "subproject" of the QA tree, build the tutorial examples where you expect them, and then run the QA scripts on them.
> 
I don’t know how to do subprojects in a GitHub repository.

I guess I should destroy my branch and recreate it in order to push the setup-env files.

	M

**Comment by jmellorcrummey** [comment]
> I don’t know how to do subprojects in a GitHub repository.

See `https://git-scm.com/book/en/v2/Git-Tools-Submodules`

> I guess I should destroy my branch and recreate it in order to push the setup-env files.

You can just delete the QA files and push your changed branch for merging.

**Comment by martyitz** [comment]
I think I pushed the correct changes.  No QA* files.

	M

**Pull request closed without merging**
