### PR TITLE
Msi3 -- remove QA files from hpctoolklit-tutorial-examples

### PR DESCRIPTION
**Pull request by martyitz**

### CODE REVIEW

**Comment by jmellorcrummey** [comment]
Why are you launching 4 MPI ranks on ufront for AMD and NVIDIA GPU test cases? We don't have 4 AMD GPUs. We only have 1 NVIDIA GPU. If you try the PC sampling test case with more than one MPI rank per GPU, PC sampling fails.

**Comment by martyitz** [comment]
Because I think 4 ranks is pretty minimal for real MPI, and one rank is odd, at best.

I know PC sampling fails with more than one rank.  I can tweak the one test.

	M

**Comment by jmellorcrummey** [comment]
The purpose of the example is not to show off MPI. The aim of the example is to show off GPU performance monitoring of a complex code.

Since the aim of the example is to show off GPU performance monitoring, we don't want to run a 4-GPU application on a machine with less than 4 GPUs of the type being launched for a GPU example.

The reason it is being run as an MPI program is because the program is built using MPI. I don't know if it even supports a build without MPI.

**Comment by martyitz** [comment]
My purpose is to use it as a test case for HPCToolkit.  We can talk more on Friday.

	M

**Pull request merged**
